### ISSUE TITLE
Files are not downloaded to the specified downloads folder

### ISSUE THREAD

**Issue by ddanzeiser** [Slyyxp/BugsPy#12]
downloads_directory is set to ~/DOWNLOADS.  Instead of the expected behavior, all album folders are placed in the current directory, with the desired directory appended to the start of the filename:

![Screenshot_2020-11-14_21-31-28](https://user-images.githubusercontent.com/9083831/99162224-ee636600-26c0-11eb-8c7d-8225cc08af2c.png)

Additionally, although the in-progress downloads appear in the correct album folder, the completed tracks are again placed in the current working directory. 

It seems that utils.sanitize() is being called on the entire file path, which replaces the slashes with underscores making it no longer a valid path. The one path that is not sanitized in this way is pre_path, which is why the in-progress downloads do not appear in the cwd but everything else does.  I made a few changes so that utils.sanitize() is only called on the actual folder name instead of the entire path and it solved the problem.  Platform is linux but this should cause issues on all platforms if I'm not mistaken.

**Comment by Slyyxp** [comment]
If you have already solved this issue you can always make a pull request.

**Comment by ddanzeiser** [comment]
I can if you'd like me to, but I'm 1) definitely not a programmer let alone a python programmer 2) have never made a pull request before so I'm gonna have to google how lmao and 3) I'm not even sure if I fixed it correctly (as in, if everything that needs to be sanitized still is)

**Comment by Slyyxp** [comment]
I'm not a programmer either. (At least professionally).
You opened up the file and fixed it, good enough for me.

All PR's are reviewed first so it doesn't matter.

The steps to open a PR are:
- Fork the repository
- Push changes to the forked repo
- Open a PR.

**Comment by Slyyxp** [comment]
Closed with https://github.com/Slyyxp/BugsPy/commit/75d7b5be74e487035cf39af07f68c3ebd287aeab
