### ISSUE TITLE
24-bit support?

### ISSUE THREAD

**Issue by snowbie** [Slyyxp/BugsPy#16]
Will 24-bit ripping functionality ever be added? Unless there's something I'm missing. iirc the massive /kpg/ torrent uses BugsPy and has 24-bit files included when they're available, but I'm unsure if they're downloaded legitimately through Bugs vs ripped

**Comment by Slyyxp** [comment]
24-bit support is not planned. Bugs do not offer any plan to stream 24-bit files, therefore these files cannot be obtained through the same process already outlined in BugsPy.
While it is entirely possible a way to access these files will be found in future, I am not personally looking into it.

/kpg/ is most definitely not using BugsPy to source their 24-bit files, and as it says on their front page: "I source most of my music from Jpopsuki".

Anyone who does have knowledge about accessing 24-bit content can open an issue or even a pull request.
