### ISSUE TITLE
[Feature request] Accept single track URL in input

### ISSUE THREAD

**Issue by awsms** [Slyyxp/BugsPy#17]
I just realized it's not possible to download single tracks with BugsPy. Could single track support be added?

This URL template for example, https://music.bugs.co.kr/track/80253599

**Comment by Slyyxp** [comment]
Client has been updated to support this.
This commit isn't something i'm proud of though as there is a lot of repeated code. It's definitely worth going back over it at some point.
https://github.com/Slyyxp/BugsPy/commit/4ce4b0745379aed41d7fe7f9561b32a8586030a8
