### ISSUE TITLE
I cannot be used normally on my windows 11

### ISSUE THREAD

**Issue by skylover007** [Slyyxp/BugsPy#19]
Since I recently upgraded to Windows 11, it has not been used normally.
Could you please let me know where I went wrong and how to fix it?
thank you.

![2021-11-12_110002](https://user-images.githubusercontent.com/35911123/141402295-c9b2e2e7-12e6-403a-baf1-ac4153cc9f55.png)

**Comment by Slyyxp** [comment]
Looks like urllib3 is missing from requirements.
Installing it will correct this.

I'll adjust requirements.txt

**Comment by skylover007** [comment]
Even after installing urllib3, it is still not possible to use it normally.
Is it correct to install like this?

And for reference, it can be used normally in Python 3.9.6.
![2021-11-12_143454](https://user-images.githubusercontent.com/35911123/141421886-6b626be3-a950-4759-a88d-9ccfa8268961.png)

**Comment by Slyyxp** [comment]
As stated in the README this repo is tested on 3.8.0.
