### ISSUE TITLE
Unable to complete the download because of the locked song or album

### ISSUE THREAD

**Issue by skylover007** [Slyyxp/BugsPy#5]
Hi~ Slyy.
First of all thank you for your works

When I try to download this [album](https://music.bugs.co.kr/album/485451), I get this error.   [09.49.56.log](https://github.com/Slyyxp/BugsPy/files/5172307/09.49.56.log)
![003](https://user-images.githubusercontent.com/35911123/92194846-320a4a00-ee9e-11ea-9764-64d31d9dbcd4.jpg)

![001](https://user-images.githubusercontent.com/35911123/92192599-e73a0380-ee98-11ea-8359-926b2f898082.jpg)

 =================================================================================

And here is another similar problem. Because of the locked album, the download of the [artist](https://music.bugs.co.kr/artist/1405)’s album cannot be completed.   
[10.04.00.log](https://github.com/Slyyxp/BugsPy/files/5172412/10.04.00.log)

![image](https://user-images.githubusercontent.com/35911123/92194414-2f5b2500-ee9d-11ea-8e44-c90a40e51912.png)

![002](https://user-images.githubusercontent.com/35911123/92194542-88c35400-ee9d-11ea-8623-dc567cc0a700.jpg)

**Comment by Slyyxp** [comment]
Closed with https://github.com/Slyyxp/BugsPy/commit/74b175fe619438a63e822c2ed1dccb5298c5e2e7
