### ISSUE TITLE
Filter artist releases from contributions

### ISSUE THREAD

**Issue by skylover007** [Slyyxp/BugsPy#6]
Thanks for fixing the bug.

The two things I'll mention below aren't bugs, but I'd like to suggest if they can be fixed.

When downloading as an artist, the [album](https://music.bugs.co.kr/artist/1405/albums) seems to receive three types of albums as shown in the image below.
 Release(발매) / Participation(참여) / Compilation(컴필레이션).

**I wish I could only get the official release album, is that possible?**

![image](https://user-images.githubusercontent.com/35911123/92220102-0bfc9e00-eece-11ea-820d-d2856927cbe4.png)
![image](https://user-images.githubusercontent.com/35911123/92220861-2c792800-eecf-11ea-9aaf-401310970dcc.png)

**Comment by Slyyxp** [comment]
I'll have a look at the API Response and see how to deal with filtering.

**Comment by skylover007** [comment]
> I'll have a look at the API Response and see how to deal with filtering.

OK, Thank you

**Comment by Slyyxp** [comment]
Closed with https://github.com/Slyyxp/BugsPy/commit/2ab1eb1a0c81eadaebe936c6525e557ec2bd3bc9

**Comment by Slyyxp** [comment]
The Bugs API does not specifically tell us whether or not an album is considered as a contribution/participation.
Cross-checking the user-provided artist id with the artist id on the album will have to do.
